---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer
  externalIPs:
  - 10.20.0.100