---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mon
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mon
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: "grafana"
          image: "grafana:latest"
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              name: grafana
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: mon
  name: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer