---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mon
  name: "alertmanager"
  labels:
    app: alertmanager
  name: alertmanager
spec:
  selector:
    matchLabels:
      app: "alertmanager"
  template:
    metadata:
      labels:
        app: "alertmanager"
    spec:
      containers:
        - name: "alertmanager"
          image: "alertmanager:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  namespace: mon
  name: "alertmanager"
spec:
  selector:
    app: "alertmanager"
  type: NodePort
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 31002